version: '3.9'

services:

  db:
    image: postgres
    restart: always
    shm_size: 128mb

    volumes:
      - type: tmpfs
        target: /dev/shm
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: store
    ports:
      - 5432:5432

  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080